version: "3.1"
services:
  postgres:
    image: "postgres:9.3"
    environment:
      POSTGRES_PASSWORD: abcABC123
      POSTGRES_USER: postgres

  logger:
    image: central-logger:latest
    build:
      context: .
      dockerfile: src/CentralLogger/Dockerfile
    depends_on:
      - "postgres"
    ports:
      - "8888:80"